[pytest]
testpaths =
    test_cases
    .

addopts =
  --html=test_cases/reports/report.html --self-contained-html
  --alluredir=test_cases/reports/allure

python_files = test_*.py
python_functions = test_*
norecursedirs = .venv venv .git node_modules
